{% set name = "launchdarkly-eventsource" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/launchdarkly_eventsource-{{ version }}.tar.gz
  sha256: cac0a158ed75f7f23e0bf83890d6a93e36a64786b154c1219282b6b4507a7a0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - urllib3 >=1.26.0,<3

test:
  imports:
    - ld_eventsource
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://docs.launchdarkly.com/sdk/server-side/python
  dev_url: https://github.com/launchdarkly/python-eventsource
  summary: LaunchDarkly SSE Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
