schema_version: 1

context:
  name: launchdarkly-eventsource
  version: "1.7.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/launchdarkly_eventsource-${{ version }}.tar.gz
  sha256: e47e32a4752e60795038deec463f63a6c6e4c20d944df155fa63036edff20450

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - urllib3 >=1.26.0,<3

tests:
  - python:
      imports:
        - ld_eventsource
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: LaunchDarkly SSE Client
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://docs.launchdarkly.com/sdk/server-side/python
  repository: https://github.com/launchdarkly/python-eventsource

extra:
  recipe-maintainers:
    - xhochy
