schema_version: 1

context:
  name: launchdarkly-eventsource
  version: "1.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/launchdarkly_eventsource-${{ version }}.tar.gz
  sha256: 8575c8d4186d439bb8f918dd13e1cc41a86d462820193d65b382e4f94cda40ff

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - urllib3 >=1.26.0,<3

tests:
  - python:
      imports:
        - ld_eventsource
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: LaunchDarkly SSE Client
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://docs.launchdarkly.com/sdk/server-side/python
  repository: https://github.com/launchdarkly/python-eventsource

extra:
  recipe-maintainers:
    - xhochy
